apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
  annotations:
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "1"
spec:
  source:
    git:
      url: https://github.com/fjb4/dotnet-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: example-rabbitmq-cluster-1
